// State de productos
export const OBTENER_PRODUCTOS_EXITO = 'OBTENER_PRODUCTOS_EXITO';

// State para el pedido
export const SELECCIONAR_PRODUCTO = 'SELECCIONAR_PRODUCTO';
export const CONFIRMAR_ORDENAR_PLATILLO = 'CONFIRMAR_ORDENAR_PLATILLO';
export const MOSTRAR_RESUMEN = 'MOSTRAR_RESUMEN';
export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO';
export const PEDIDO_ORDENADO = 'PEDIDO_ORDENADO';


export const SET_USERDATA = 'SET_USERDATA';
export const SET_COUNTER = 'SET_COUNTER';
export const SET_MY_COUNTERS = 'SET_MY_COUNTERS';
export const SET_SUSCRIPTIONS = 'SET_SUSCRIPTIONS';